devices/debian.py

devices: debian: don't mess with eth1 if ip address is already set

---

devices/base.py

devices: base: add func to get ipv6 addr

---

devices/dell_switch.py

This let's us add more VLANs to a specific port without effecting it's
previous functionality of having a private container on the primary VLAN
associated with the port

devices: dell_switch: add addl vlans to port

---

deploy-boardfarm-nodes.sh

You can create a static wan node via the following:
$ . ./deploy-boardfarm-nodes.sh
$ set -x; IFACE=eth1 create_container_eth1_static wan-shared 172.16.1.154 172.16.1.1; set +x
$ ssh root@172.16.1.154
The static ip address and the default gateway are the 2nd and 3rd argument

deploy-boardfarm-script: add option for static wan node

---

devices/debian.py

It's possible to have a container that has no eth0 and eth1 is the only
connected interface to the board and outside. So let's add an option to
skip using that interface

devices: debian: add wan-no-eth0 option

---

devices/debian.py

This only starts a ipv6 server so far, it does not copy the provisioning
files, it does not setup provisioning per device, it does not check the
CMTS (or change the CMTS) to be in the right provisioning mode.
Signed-of-by: Rachel Lei <rlei@libertyglobal.com>
MSM: Various updates and comments added, reworked commit message

devices: debian: support ipv6 dhcp srever

---

devices/dell_switch.py

This is just an example config, but don't make this port private for now

devices: dell_switch: don't make port 36 private

---

devices/casa_cmts.py

This waits properly for various connection methods to be established
before attempting to run commands

devices: casa_cmts: update to use connection decider

---

requirements.txt
tests/bittorrent.py

tests: bittorrent: add a basic test to simulate bittorrent

---

devices/casa_cmts.py

1. Add logout and clear_offline function
2. Add check_online function
3. Add check_PartialService function
4. Add get cm ip and mta ip

Pr add casa cmts function

---

devices/casa_cmts.py

1. Add C10 CMTS type
2. Add add modify_docsis_mac_ip_provisioning_mode.

Pr add casa cmts function v2

---

devices/debian.py

devices: debian: more fixups for installing packages

---

devices/windows_telnet.py

modify set_fixip to set_static_ip
Signed-off-by: Nero_Chen <nero_chen@compalbn.com>

devices: windows_telnet.py: modify function name

---

devices/debian.py
devices/windows_telnet.py
tests/cdrouter_bootstrap.py

@SyHuangCBN please do a quick review.... we will have to resolve some issues as we run into them

Pr add more config to cdrouter

---

bft

bft: skip test if not found

---

devices/power.py

To test:
>>> from devices import power
>>> power.PX2('10.64.51.3', '1').reset()

devices: power: add simple power/reset for PX2 PDU

---

.travis.yml
testsuites.cfg

travis: add travisci testsuite for automated test

---

zephyr/zapi.py
zephyr/zephyr_reporter.py

Pr more small zephyr fixes

---

devices/debian.py

Keep static route for wan with the 'wan-' prefix and make this work for
both wan and lan if required.
This let's us keep static routes set for wan and lan devices. The use
case here is to keep the main SSH connection established to the device.

devices: debian: make static route for lan device as well

---

tests/oe.py

tests: oe: skip if oe version is not present

---

devices/__init__.py

devices: improved warning reporting when board model not found

---

deploy-boardfarm-nodes.sh

We still default to bft:node tagged image, but this can be set via env
variable before calling functions or running the script

deploy: update docker container image name to be configurable

---

tests/lib/installers.py

-tests:lib:installers.py:add install_pysnmp
add install pysnmp setup
Signed-off-by: MartinCBN <martin_wu@compalbn.com>

add tests: lib : installers.py: add install_pysnmp

---

tests/webbrowse.py

Testing these URLs coudl take some time, so let's touch the board in
between

tests: webbrowse: keep the board alive

---

devices/__init__.py

One type of error mostly will generate issues here, otherwise just
passthrough the exception for handling later

devices: improve error messages

---

.gitignore

gitignore: update for more entries

---

devices/axiros_acs.py

devices: axiros: remove debug prints that snuck in

---

devices/debian.py

This let's us control DNS and route all dns through our WAN node

devices: debian: start and run a dns relay server

---

deploy-boardfarm-nodes.sh

deploy-boardfarm-nodes: add static ip option with docker network intact

---

tests/lib/installers.py

-tests: lib: installers.py: modified telnet prompt
modified install_telnet_server and install_telnet_client prompt
add telnet server ipv6 setup
Signed-off-by: MartinCBN <martin_wu@compalbn.com>

tests: lib: installers.py: modified telnet prompt

---

devices/casa_cmts.py
tests/lib/installers.py

Added function in installers to install upnp and tcpick.

tests:lib:installers.py: add install_upnp ,install_tcpick

---

tests/lib/regexlib.py

this should become a one stop shop for common regex

tests: lib: regexlib.py regular expressions library

---

devices/casa_cmts.py

-function get_cmip: updated function to modify cmmac as seen in CMTS
-get_cmipv6 function is added to get cm ipv6 address from cmts
Signed-off-by: Prem Kumar K N <prekumar.contractor@libertyglobal.com>

devices: casa_cmts: updated with improvements

---

tests/lib/mta_conf.tcl

Fix "expected integer but got "0x"" issue
Signed-off-by: lynn <lynn_lin@compalbn.com>

tests: lib: mta_conf.tcl: fix 9_MTA_EU_CBN_SIP20_Basic.BIN decode issue

---

devices/debian.py

This will be the device that is connected to the dut, we always used
eth1 but this can really be any device and need to get away from the
hard coded value

devices: debian: add iface_dut to replace eth1 hardcoded

---

devices/openwrt_router.py

if the user is found, swallow the  prompt then returns

devices: openwrt_router: fixed a bug

---

devices/casa_cmts.py

devices: casa_cmts: use full form of show cable modem

---

testsuites.py

testsuites: add support for layerconf list testsuites

---

html/template_results.html
make_human_readable.py

Show location, show device types connected but leave off other details

html: fixup some html results

---

bft

bft: exit with message if unable to find testsuite

---

bft

the test case files now have a header with the TC name and docstring
and the footer lines have a separator

bft: added header and modified footer for result/tc_name.txt logs

---

devices/debian.py

in get_interface_ipaddr() added match for
inet 10.8.0.1  netmask 255.255.255.0  destination 10.8.0.1

Pr match tun0 interface

---

tests/rootfs_boot.py

tests: rootfs_boot: only route traffic if we are a debian based prov

---

devices/__init__.py

There may be a chance in the future for kermit to be used
instead of telnet (as the latter seem to be taking 100% cpu for
no apparent reason!)

devices: __init__: added check for kermit installation

---

bft

bft: remove unused imports

---

tests/lib/installers.py
tests/lib/scripts/openvpn-install.sh

Installs for OpenVPN and PPTP
Committed the configuration scrip openvpn-install.sh
but not yet integrated.

tests: lib: installers: added vpn install functions

---

deploy-boardfarm-nodes.sh

deploy-boardfarm-nodes: add ipvlan (vs macvlan) option for containers

---

boardfarm_config_example.json

boardfarm config: move proxy info to correct device

---

tests/jmeter.py

Also comment out all the lines regarding copying results

tests: jmeter: increase java heap size

---

tests/lib/gui_helper.py
tests/lib/wifi.py

wifi.py - Modified function name for stub class
Signed-off-by: Kalpana Vetrivel <kvetrivel.contractor@libertyglobal.com>

 gui_helper.py - Added importing modules

---

devices/debian.py
tests/lib/docsis.py
tests/rootfs_boot.py

tests: lib: docsis: add stub for cm_cfg and making changes

---

tests/lib/installers.py

the regex did not catch a file name
the expect prompt moved to anthoer line

tests: lib: installers: bug fix

---

tests/lib/installers.py

- latest installation of postfix in linux do not expect parameters
- Modified the function to work both with/without parameters
Signed-off-by: prekumar.contractor<prekumar.contractor@libertyglobal.com>

tests: lib: installers: modified install_postfix function

---

devices/windows_telnet.py

add get_default_gateway function for get wifi interface gateway IP.
Signed-off-by: Nero_Chen <nero_chen@compalbn.com>

devices: windows_telnet: add get_default_gateway

---

bft

Move test_cases_list.append([]) to tc for loop to fix list index out of range, Unable to Update results in Zephyr issue.
Signed-off-by: lynn <lynn_lin@compalbn.com>

bft: fix update the results in Zephyr issue

---

devices/base.py
tests/interact.py
tests/rootfs_boot.py

devices: base: added set_printk, updated interact.py and rootfs_boot.py

---

devices/debian.py
devices/debian_isc.py

retrieves a file form the tftp server to the localhost.

device: debian: retrieves a file form the tftp to the localhost

---

tests/lib/installers.py

tests: lib: installers: bugfix for VPN over ipv6

---

devices/casa_cmts.py

Signed-off-by: Panimalar Palaniappan <ppalanaiappan.contractor@libertyglobal.com>

devices: casa_cmts: added function to get erouter ipv4 and ipv6 from cmts

---

tests/lib/common.py

snmp_mib_set() - Modified for reg-ex for getting hex-string value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/290)

tests: lib: common.py

---

devices/casa_cmts.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/291)

devices : casa_cmts: Modified the grouping in get_ertr_ipv4()

---

tests/lib/gui_helper.py

add select option by name for GUI
Signed-off-by: gerben <gerben_chen@compalbn.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/288)

lib: gui_helper: add select option by name for GUI

---

tests/lib/wifi.py

Signed-off-by: Kalpana Vetrivel <kvetrivel.contractor@libertyglobal.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/295)

lib: wifi: Added "self" argu for func in wifi_stub() class

---

tests/lib/common.py

Signed-off-by: Panimalar Palaniappan <ppalanaiappan.contractor@libertyglobal.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/292)

tests: lib: common.py - Modified snmp_mib_get to replace ""

---

tests/lib/network_helper.py

because the old one is for py3 version,fix it for py2 version
Signed-off-by: samuel <samuel_chuang@compalbn.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/303)

fix tests: lib: network_helper

---

tests/lib/gui_helper.py

add function for get text value by xpath
gui element has no element id to use
Signed-off-by: gerben <gerben_chen@compalbn.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/304)

lib: gui_helper: add get_text_value_by_xpath

---

tests/lib/gui_helper.py

add function for select by xpath
Signed-off-by: gerben <gerben_chen@compalbn.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/312)

lib: gui_helper: add select_option_by_xpath function

---

devices/casa_cmts.py

This change is required for the below commit, I will re-open the commit once the dependency gets merged
http://172.16.1.237:8080/c/boardfarm-cbn/+/3240
Signed-off-by: Panimalar Palaniappan <ppalanaiappan.contractor@libertyglobal.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/310)

devices: casa_cmts.py: added clear_cm_reset() to reset the CM from CMTS

---

devices/casa_cmts.py

-Function checks the encrytion mode and returns True if online
-Function returns actual status if status other than online
-Encryption enable(yes) - online(pt), (no)-online
-Asserts when the above conditions are not met
Signed-off-by: prekumar.contractor <prekumar.contractor@libertyglobal.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/313)

devices: casa_cmts: updated check_online function

---

tests/lib/wifi.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/315)

tests: lib: wifi: Added wifi_client_stub()

---

tests/lib/common.py

add -c community setup for using public
Signed-off-by: MartinCBN <martin_wu@compalbn.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/314)

tests: lib: common: modified snmp_mib_get

---

devices/debian.py

Modified the functions to perform in sudo as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/308)

devices: debian: Enhanced link_up() and set_link_state()

---

devices/debian_wifi.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/307)

devices: debian_wifi: Enhanced the wifi functions to execute in sudo as well

---

.travis.yml

Change-Id: Iac22548602743948e9353dab1311eda1436109bf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/331)

.travis.yml: lock down dist to test on

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/336)

Add pip install to travis.yml
