lgirdk/boardfarm

bft, devices/debian.py, devices/openwrt_router.py, tests/ping.py
This was also called get_interface_ipaddr, so let's just use one
=> bft: remove duplicate get_ip_addr

devices/base.py, devices/error_detect.py
Now we print the correct calling function for expect or send functions
when BFT_DEBUG is set in the environment
=> devices: base: fix stack offsets for expect helper

devices/rpi.py
This will flash a complete SD image after Linux is booted. This is done
incase u-boot env sector is corrupt or you just want to risk flashing an
entire image.
If the image is bad, the board will be bricked
=> devices: rpi3: add support to flash complete SD image

bft
Make a generic way for tests to save results to a file. This is an
example how to use this:
```
import rootfs_boot
import pexpect
from devices import board, wan, lan, wlan, prompt
class FooBar(rootfs_boot.RootFSBootTest):
def runTest(self):
board.expect(pexpect.TIMEOUT, timeout=5)
self.log_to_file = "WRITE THIS TO FILE"
```
=> bft: add ability for test to specific results to log to file

.travis.yml, devices/qemu.py, tests/rootfs_boot.py
We can also enable networking since this will route traffic between the
WAN and LAN devices
=> travis: update image to point at RDK-B qemu image

devices/casa_cmts.py
When logout to exit cmts, it missed "exit" command to cmts terminal for 2 layer.
Add exit command.
Signed-off-by: sy_huang <sy_huang@compalbn.com>
=> devices: casa_cmts.py: fix logout issue

devices/base.py
Fix regexp to get ipv6 function
ex:
inet6 addr: fe80::40ec:26b8:95a5:1132/64
function return 'fe80::40ec:26b8:95a5:1132/64' change to 'fe80::40ec:26b8:95a5:1132'
Signed-off-by: luke_tseng <luke_tseng@compalbn.com>
=> devices: base.py:fix_get_interface_ip6addr

devices/windows_telnet.py
This connects to a windows machine over telnet. Here is a basic example
test:
```
from devices import winwifi
class wintest(rootfs_boot.RootFSBootTest):
def runTest(self):
winwifi.sendline('dir')
winwifi.expect(winwifi.prompt)
```
You can add a device in the boarfarm config via:
```
"devices": [
{
"name": "winwifi",
"type": "windows-telnet",
"ipaddr": "$ipaddr",
"username": "user",
"password": "pass"
}
```
=> devices: windows_telnet: add inital device for a windows telnet device

devices/debian.py
If a test needs to know the tftp server IP address that the DUT can see
then they need to use this function to parse it
=> devices: debian: add functio nto extract tftp server ip address

tests/screenshot_gui.py
Start vnc server if available, and then print a message and wait for
user to connect if BFT_DEBUG is set in env... fallback to Xvfb
otherwise.
Close display after we are done in recover()
=> tests: screenshot_gui: add some debug provisions

devices/local_cmd.py
This will simply fail if we don't connect to the device via this
comamnd. Let's raise an exception instead so it backs out and trys
another board if one is available
=> devices: local_cmd: skip to next device if cmd closes

deploy-boardfarm-nodes.sh
Wake up these containers so the upstream switch knows about these mac addresses
=> deploy-boardfarm-nodes: ping default route

make_human_readable.py
This fixes regressions where we did not use the template in the html dir
=> html: scan all overlays for html and use first one in overlay list

deploy-boardfarm-nodes.sh
Previous commit changed this from the default docker route, so let's just
ask the interface instead
=> deploy-boardfarm-nodes: pick docker0 as interface to route via

devices/debian.py, tests/rootfs_boot.py
We do a lot more things in the configure step now including turn off
eth1 and trying to install packages from the host network so it will
leave us in a bad state, so let's start the tftp server right after that
and then also make sure the interface is up
=> tests: rootfs_boot: start tftp server after configure

tests/lib/docsis.py
- add docsis class for cfg file to decode and encode.
Name: docsis module
Purpose: docsis operating.
Input: Absolute path of text file
Fuction:
decode():
return output file name(.txt)
encode(output_type='cm_cfg')
return output file name(.cfg or .bin)
Signed-off-by: luke <luke_tseng@compalbn.com>
=> tests: lib: docsis.py: add docsis class for cfg file opartion

tests/lib/docsis.py
-change docsis encode output name
ex: docsis(file_abspath).encode('cm_cfg') will return mv1-1-1/mv1-1-1-cm.cfg
Signed-off-by: luke <luke_tseng@compalbn.com>
=> tests: lib: docsis.py: modify docsis class for independent policy

devices/casa_cmts.py
increased the value of 2 timeouts in CasaCMTS.connect that seemed too optimistic
3s -> 10s
5s -> 20s
=> devices: casa_cmts: timeout increase

tests/screenshot_gui.py
So we can run recover properly
=> tests: screenshot_gui: save display in self.display

devices/casa_cmts.py
This will help some CMs come online faster
=> devices: casa_cmts: add early auth encry ranging option

devices/base.py
- self.before.strip() instead of self.before
Signed-off-by: luke <luke_tseng@compalbn.com>
=> devices: base.py: add .strip() to return string

deploy-boardfarm-nodes.sh
$ . deploy-boardfarm-nodes.sh
$  random_private_mac
00:16:3e:30:83:f0
=> deploy-boardfarm-nodes: fix random mac function

tests/lib/docsis.py, tests/lib/mta_conf.tcl
Fix mta config file encode issue by mta_conf.tcl tool.
MTA configure file Encode/Decode rev.1.0.0
Usage:tclsh mta_conf.tcl input_file [option]
option:
[General]
-e        Encode a MTA configuration file
-d        Decode a MTA configuration file
-m        Use MD5 as config file hash signature (default is SHA1)
-hash     Add config hash (non (default), na, eu)
-out      Specify a output filename (for encode use)
ex.tclsh mta_conf.tcl mta.txt -e -hash eu
Signed-off-by: lynn <lynn_lin@compalbn.com>
=> tests/lib: docsis.py: fix mta config file encode issue_v2

devices/debian.py
In bridged mode the lan_gateway will (most likely) not be the gateway
for the lan device. So we will update our lan_{gateway,network}
attributes.
Secondly, no reason to del the default route and add it back let's just
keep that set.
=> devices: debian: fix issues with bridged mode

devices/casa_cmts.py
helper function to convert a mac from XX:XX:XX:XX:XX:XX
to xxxx.xxxx.xxxx (casa cmts output format)
=> devices: casa_cmts: added get_cm_mac_cmts_format(mac)

config.py, tests/screenshot_gui.py
added:
"disp":["xvfb", "xephyr", "xvnc"],
"disp_port":["5904"],
"disp_size":["1366x768"]
with defaults:
default_display_backend = "xvnc"
default_display_backend_port = "5904"
default_display_backend_size = "1366x768"
screenshot_gui updated accordingly
=> config: updated BFT_OPTIONS

devices/debian.py
Sometimes we share these devices among multiple other devices esp. when
running as a provisioner so let's not delete all the files
TODO: find out how to cleanup...
=> devices: debian: don't delete tftp files if server is shared

tests/lib/logging.py, tests/linux_boot.py
Requested by the test architect, time is shown as follows:
====== Begin NTL7465LG__P3__541         Start Time: Sat 12 Jan 2019 22:05:31  ====
====== End NTL7465LG__P3__541           End Time: Sat 12 Jan 2019 22:15:31  ==
=> tests: linux_boot: now displays the test start/end time

html/template_results.html, make_human_readable.py
For NTL require, need report completion time inside result.html.
Photos attached with this modify.
Signed-off-by: gerben <gerben_chen@compalbn.com>
Board access:
•Report completion time: 2018-12-19 20:52:34
•Name: mv1-2-2
•Router console: [u'telnet 172.16.1.217 7003', u'telnet 172.16.1.217 7004']
•Location: taiwan-wifi-2
•wan debian
•lan debian
•provisioner cisco-cnr
•acs_server friendly_acs_soap
•wifi_2G cbn_wifi_2G
•wifi_5G cbn_wifi_5G
•cmts casa_cmts
=> html: template_results.html ; make_human_readable.py

devices/openwrt_router.py
The previouos regex mathed against ip addresses as well.
=> devices: openwrt_router: regex fix

tests/lib/common.py, tests/lib/installers.py
-postfix server is used to install SMTP servers locally
tests: lib: common: added function to configure postfix SMTP server
-As of now function configures postfix to allow access for clients on TLS and SSL port numbers
-The function can be extended to configure mail server and for mail communication
Signed-off-by: Prem Kumar K N <prekumar.contractor@libertyglobal.com>
=> tests: lib: installers: added function to install postfix

tests/lib/installers.py
Now use the committed openvpn-install.sh instead of curling it
every time. The curl line was left for reference (commented out).
=> tests: lib: installers: the openvpn-install.sh is no longer curled

devices/base.py
- Added code to enable sysctl knob to accept router advertisement
- accept_ra value is set to 2 which override ipv6 forwarding rule
and accepts ra
Signed-off-by: prekumar.contractor<prekumar.contractor@libertyglobal.com>
=> devices: base: enahnaced "enable_ipv6" function

devices/debian.py
When copying a file to a server the device did not have xxd installed
and the copy failed without an error message.
This makes sure xxd is installed.
=> devices: debian: install xxd in device (copy_file_to_server related)

tests/lib/docsis.py
- added _cm_configmode function to get the config mode based on
1. TLV code 2. InitializationMode
- 0-Disable/Bridge, 1-IPv4, 2-IPv6 (DSlite), 3-IPv4 and IPv6(Dual)
- this function addresses the comments from
https://github.com/lgirdk/boardfarm/pull/263
Signed-off-by: prekumar.contractor <prekumar.contractor@libertyglobal.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/287)
=> tests: lib: docsis: added method to check Config mode in CM

devices/base.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/289)
=> devices: base: set_printk is wrapped in a try/except block

tests/lib/common.py
- The match group result has the additional space at the end
- Modified the match group to fetch without space
Signed-off-by: prekumar.contractor <prekumar.contractor@libertyglobal.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/311)
=> tests: lib: common: modified snmp_mib_get for additional space

tests/lib/network_testing.py
tcpdump_capture() - Start the tcpdump capture
tcpdump_read() - Read the tcpdump capture
nmap_cli() - Execute the nmpa cli
kill_process() - Kill the process
ping() - ping of an IP
This change is required as per comments provided for the commit http://172.16.1.237:8080/c/boardfarm-cbn/+/2934
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/309)
=> tests: lib: network_testing: Added generic functions for network testing

.travis.yml
Without this package, a user can hit this error:
File "/home/ubuntu/boardfarm/devices/debian_isc.py", line 5, in <module>
from lib.docsis import docsis, cm_cfg
File "/home/ubuntu/boardfarm/devices/../tests/lib/docsis.py", line 11, in <module>
import Tkinter
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
raise ImportError, str(msg) + ', please install the python-tk package'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lgirdk/boardfarm/319)
=> Add python-tk to travis.yaml
